terraform state rm aws_default_network_acl.main
terraform state rm aws_ecs_cluster.app_cluster
terraform state rm aws_ecs_service.app
terraform state rm aws_ecs_task_definition.app
terraform state rm aws_iam_role.task_execution_iam_rolev2
terraform state rm aws_internet_gateway.main
terraform state rm aws_route.rt1
terraform state rm aws_route.rt2
terraform state rm aws_security_group.main
terraform state rm aws_subnet.subnet1
terraform state rm aws_vpc.main
